
const products= [
    {
       id:"1",
        title: "Abaya",
        like: true,
        img: 'https://res.cloudinary.com/dgeib3q2u/image/upload/v1673440538/cld-sample-5.jpg',
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
        price: 10000,
        countInStock:10,
        rating:4,
        numReviews:4,
    },
    {
        id:"2",
        title: "Abaya",
        like: false,
         img:'https://res.cloudinary.com/dgeib3q2u/image/upload/v1673440538/cld-sample-5.jpg',
         desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
         price: 10000,
         countInStock:10,
         rating:4,
         numReviews:4,
     },
     { 
        id:"3",
         title: "Abaya",
         like: true,
        img: 'https://res.cloudinary.com/dgeib3q2u/image/upload/v1673440538/cld-sample-5.jpg',
         desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
         price: 10000,
         countInStock:10,
         rating:4,
         numReviews:4,
     },
     {
        id:"4",
         title: "Abaya",
         like: false,
         img:'../src/Images/abaya.png',
         price: 10000,
         countInStock: 10,
         rating:4,
         numReviews:4,
     },
     {
        id:"5",
         title: "Abaya",
         like: true,
         img: 'https://res.cloudinary.com/dgeib3q2u/image/upload/v1673440538/cld-sample-5.jpg',
         desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
         price: 10000,
         countInStock:10,
         rating:4,
         numReviews:4,
     },
     {
        id:"6",
         title: "Abaya",
         like: true,
         img: '../src/Images/abaya.png',
         price: 10000,
         countInStock:10,
         rating:4,
         numReviews:4,
     },
     {
        id:"7",
         title: "Abaya",
         like: false,
         img: 'https://res.cloudinary.com/dgeib3q2u/image/upload/v1673440538/cld-sample-5.jpg',
         desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
         price: 10000,
         countInStock:10,
         rating:4,
         numReviews:4,
     },
     {
        id:"8",
         title: "Abaya",
         like: true,
         img: 'https://res.cloudinary.com/dgeib3q2u/image/upload/v1673440538/cld-sample-5.jpg',
         desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
         price: 10000,
         countInStock:10,
         rating:4,
         numReviews:4,
     },
 ]; 
module.exports=products
 
//export default products;